// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

// 定义包名

package probuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LogReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Role                 int64    `protobuf:"varint,4,opt,name=role,proto3" json:"role,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Type                 string   `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	Code                 string   `protobuf:"bytes,8,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogReq) Reset()         { *m = LogReq{} }
func (m *LogReq) String() string { return proto.CompactTextString(m) }
func (*LogReq) ProtoMessage()    {}
func (*LogReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *LogReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogReq.Unmarshal(m, b)
}
func (m *LogReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogReq.Marshal(b, m, deterministic)
}
func (m *LogReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogReq.Merge(m, src)
}
func (m *LogReq) XXX_Size() int {
	return xxx_messageInfo_LogReq.Size(m)
}
func (m *LogReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LogReq.DiscardUnknown(m)
}

var xxx_messageInfo_LogReq proto.InternalMessageInfo

func (m *LogReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LogReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LogReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *LogReq) GetRole() int64 {
	if m != nil {
		return m.Role
	}
	return 0
}

func (m *LogReq) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *LogReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LogReq) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *LogReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type LogRes struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Role                 int64    `protobuf:"varint,4,opt,name=role,proto3" json:"role,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Type                 string   `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	UserId               string   `protobuf:"bytes,8,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogRes) Reset()         { *m = LogRes{} }
func (m *LogRes) String() string { return proto.CompactTextString(m) }
func (*LogRes) ProtoMessage()    {}
func (*LogRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *LogRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogRes.Unmarshal(m, b)
}
func (m *LogRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogRes.Marshal(b, m, deterministic)
}
func (m *LogRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogRes.Merge(m, src)
}
func (m *LogRes) XXX_Size() int {
	return xxx_messageInfo_LogRes.Size(m)
}
func (m *LogRes) XXX_DiscardUnknown() {
	xxx_messageInfo_LogRes.DiscardUnknown(m)
}

var xxx_messageInfo_LogRes proto.InternalMessageInfo

func (m *LogRes) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LogRes) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LogRes) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *LogRes) GetRole() int64 {
	if m != nil {
		return m.Role
	}
	return 0
}

func (m *LogRes) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *LogRes) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LogRes) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *LogRes) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func init() {
	proto.RegisterType((*LogReq)(nil), "probuf.LogReq")
	proto.RegisterType((*LogRes)(nil), "probuf.LogRes")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x91, 0xcd, 0x4a, 0xc4, 0x30,
	0x14, 0x85, 0x8d, 0x33, 0x4d, 0xc7, 0x0b, 0xba, 0xb8, 0x88, 0x5c, 0x66, 0x35, 0x74, 0x35, 0x6e,
	0xba, 0x50, 0x5f, 0xc0, 0xa5, 0x30, 0xab, 0x82, 0x0f, 0x90, 0x69, 0xae, 0xa3, 0xd0, 0xf6, 0xc6,
	0xa4, 0x45, 0x7c, 0x35, 0x17, 0x3e, 0x9b, 0x24, 0x69, 0x05, 0xdf, 0xc0, 0xdd, 0xf9, 0xbe, 0xfc,
	0x70, 0xe0, 0xc0, 0xa5, 0x69, 0x5b, 0x99, 0x86, 0xb1, 0x76, 0x5e, 0x46, 0x41, 0xed, 0xbc, 0x1c,
	0xa7, 0x97, 0xea, 0x4b, 0x81, 0x3e, 0xc8, 0xa9, 0xe1, 0x77, 0x44, 0x58, 0x0f, 0xa6, 0x67, 0x52,
	0x3b, 0xb5, 0xbf, 0x68, 0x52, 0xc6, 0x6b, 0x28, 0xb8, 0x37, 0x6f, 0x1d, 0x9d, 0x27, 0x99, 0x21,
	0x5a, 0xf7, 0x2a, 0x03, 0xd3, 0x2a, 0xdb, 0x04, 0xf1, 0xbd, 0x97, 0x8e, 0x69, 0xbd, 0x53, 0xfb,
	0x55, 0x93, 0x32, 0x12, 0x94, 0xc6, 0x5a, 0xcf, 0x21, 0x50, 0x91, 0xee, 0x2e, 0x88, 0x5b, 0xd8,
	0x38, 0x13, 0xc2, 0x87, 0x78, 0x4b, 0x3a, 0x1d, 0xfd, 0x72, 0xfc, 0x69, 0xfc, 0x74, 0x4c, 0x65,
	0x6e, 0x12, 0x73, 0x74, 0xad, 0x58, 0xa6, 0x4d, 0x76, 0x31, 0x57, 0xdf, 0x4b, 0xf9, 0xf0, 0xcf,
	0xcb, 0xdf, 0x80, 0x9e, 0x02, 0xfb, 0x27, 0x3b, 0xd7, 0x9f, 0xe9, 0xee, 0x01, 0xca, 0xc7, 0x3c,
	0x0b, 0xde, 0x42, 0x71, 0x90, 0xd3, 0xb3, 0xc3, 0xab, 0x3a, 0x4f, 0x53, 0xe7, 0x59, 0xb6, 0x7f,
	0x39, 0x54, 0x67, 0x47, 0x9d, 0x26, 0xbc, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x7f, 0xc8, 0xa0,
	0xa5, 0xd3, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountClient is the client API for Account service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountClient interface {
	LogUp(ctx context.Context, in *LogReq, opts ...grpc.CallOption) (*LogRes, error)
}

type accountClient struct {
	cc *grpc.ClientConn
}

func NewAccountClient(cc *grpc.ClientConn) AccountClient {
	return &accountClient{cc}
}

func (c *accountClient) LogUp(ctx context.Context, in *LogReq, opts ...grpc.CallOption) (*LogRes, error) {
	out := new(LogRes)
	err := c.cc.Invoke(ctx, "/probuf.Account/LogUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServer is the server API for Account service.
type AccountServer interface {
	LogUp(context.Context, *LogReq) (*LogRes, error)
}

// UnimplementedAccountServer can be embedded to have forward compatible implementations.
type UnimplementedAccountServer struct {
}

func (*UnimplementedAccountServer) LogUp(ctx context.Context, req *LogReq) (*LogRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogUp not implemented")
}

func RegisterAccountServer(s *grpc.Server, srv AccountServer) {
	s.RegisterService(&_Account_serviceDesc, srv)
}

func _Account_LogUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).LogUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/probuf.Account/LogUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).LogUp(ctx, req.(*LogReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Account_serviceDesc = grpc.ServiceDesc{
	ServiceName: "probuf.Account",
	HandlerType: (*AccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LogUp",
			Handler:    _Account_LogUp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.proto",
}
